"""Generated graph tables. Do not edit by hand; run `graph-model compile-graph`."""

from __future__ import annotations

from .graph_tables import CompiledGraphTables

GRAPH_PAYLOAD = {'name': 'coding-supergraph',
 'version': '0.1.0',
 'schema_hash': '1b3da7aa892798987fad830163c05aedcf17494f08a1ee483b576facb3ac909a',
 'node_ids': ['abort',
              'context',
              'diagnose',
              'finish',
              'implement',
              'intake',
              'plan',
              'plan_check',
              'repair',
              'review',
              'tests'],
 'edge_keys': ['context->implement:fast-path',
               'context->plan:planned-path',
               'diagnose->repair:always',
               'implement->tests:always',
               'intake->context:always',
               'plan->plan_check:always',
               "plan_check->abort:data.verdict == 'fail' and data.plan_revision_count >= 2",
               "plan_check->implement:data.verdict == 'pass'",
               'plan_check->plan:revise-plan',
               'repair->tests:always',
               "review->abort:data.verdict == 'fail' and data.repair_count >= 2",
               'review->diagnose:review-repair',
               "review->finish:data.verdict == 'pass'",
               "tests->abort:data.verdict == 'fail' and data.repair_count >= 2",
               'tests->diagnose:test-repair',
               "tests->review:data.verdict == 'pass'"],
 'edge_sources': [1, 1, 2, 4, 5, 6, 7, 7, 7, 8, 9, 9, 9, 10, 10, 10],
 'edge_targets': [4, 6, 8, 10, 1, 7, 0, 4, 6, 10, 0, 2, 3, 0, 2, 9],
 'edge_priorities': [100.0,
                     90.0,
                     100.0,
                     100.0,
                     100.0,
                     100.0,
                     80.0,
                     100.0,
                     90.0,
                     100.0,
                     80.0,
                     90.0,
                     100.0,
                     80.0,
                     90.0,
                     100.0],
 'edge_max_traversals': [1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 3],
 'edge_conditions': ["data.route == 'fast'",
                     "data.route in {'deep', 'repair'}",
                     'always',
                     'always',
                     'always',
                     'always',
                     "data.verdict == 'fail' and data.plan_revision_count >= 2",
                     "data.verdict == 'pass'",
                     "data.verdict == 'fail' and data.plan_revision_count < 2",
                     'always',
                     "data.verdict == 'fail' and data.repair_count >= 2",
                     "data.verdict == 'fail' and data.repair_count < 2",
                     "data.verdict == 'pass'",
                     "data.verdict == 'fail' and data.repair_count >= 2",
                     "data.verdict == 'fail' and data.repair_count < 2",
                     "data.verdict == 'pass'"],
 'allowed_edge_mask': [[False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [True,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        True,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        True,
                        True,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        True,
                        True]],
 'terminal_mask': [True, False, False, True, False, False, False, False, False, False, False]}

COMPILED_GRAPH = CompiledGraphTables(
    name=GRAPH_PAYLOAD['name'],
    version=GRAPH_PAYLOAD['version'],
    schema_hash=GRAPH_PAYLOAD['schema_hash'],
    node_ids=tuple(GRAPH_PAYLOAD['node_ids']),
    edge_keys=tuple(GRAPH_PAYLOAD['edge_keys']),
    edge_sources=tuple(GRAPH_PAYLOAD['edge_sources']),
    edge_targets=tuple(GRAPH_PAYLOAD['edge_targets']),
    edge_priorities=tuple(GRAPH_PAYLOAD['edge_priorities']),
    edge_max_traversals=tuple(GRAPH_PAYLOAD['edge_max_traversals']),
    edge_conditions=tuple(GRAPH_PAYLOAD['edge_conditions']),
    allowed_edge_mask=tuple(tuple(row) for row in GRAPH_PAYLOAD['allowed_edge_mask']),
    terminal_mask=tuple(GRAPH_PAYLOAD['terminal_mask']),
)
