"""Generated graph tables. Do not edit by hand; run `graph-model compile-graph`."""

from __future__ import annotations

from .graph_tables import CompiledGraphTables

GRAPH_PAYLOAD = {'name': 'coding-supergraph',
 'version': '0.3.0',
 'schema_hash': '1536e86a64cbf09a1c0308ab72985a67eba47eb748f3b4f7ba23accc25e7543f',
 'node_ids': ['abort',
              'apply',
              'context',
              'diagnose',
              'finish',
              'implement',
              'intake',
              'plan',
              'plan_check',
              'repair',
              'review',
              'tests'],
 'edge_keys': ["apply->abort:data.verdict == 'fail' and data.repair_count >= 2",
               'apply->diagnose:apply-repair',
               "apply->tests:data.verdict == 'pass'",
               'context->implement:fast-path',
               'context->plan:planned-path',
               'diagnose->repair:always',
               'implement->apply:always',
               'intake->context:always',
               'plan->plan_check:always',
               "plan_check->abort:data.verdict == 'fail' and data.plan_revision_count >= 2",
               "plan_check->implement:data.verdict == 'pass'",
               'plan_check->plan:revise-plan',
               'repair->apply:always',
               "review->abort:data.verdict == 'fail' and data.repair_count >= 2",
               'review->diagnose:review-repair',
               "review->finish:data.verdict == 'pass'",
               "tests->abort:data.verdict == 'fail' and data.repair_count >= 2",
               'tests->diagnose:test-repair',
               "tests->review:data.verdict == 'pass'"],
 'edge_sources': [1, 1, 1, 2, 2, 3, 5, 6, 7, 8, 8, 8, 9, 10, 10, 10, 11, 11, 11],
 'edge_targets': [0, 3, 11, 5, 7, 9, 1, 2, 8, 0, 5, 7, 1, 0, 3, 4, 0, 3, 10],
 'edge_priorities': [80.0,
                     90.0,
                     100.0,
                     100.0,
                     90.0,
                     100.0,
                     100.0,
                     100.0,
                     100.0,
                     80.0,
                     100.0,
                     90.0,
                     100.0,
                     80.0,
                     90.0,
                     100.0,
                     80.0,
                     90.0,
                     100.0],
 'edge_max_traversals': [1, 2, 3, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 3],
 'edge_conditions': ["data.verdict == 'fail' and data.repair_count >= 2",
                     "data.verdict == 'fail' and data.repair_count < 2",
                     "data.verdict == 'pass'",
                     "data.route == 'fast'",
                     "data.route in {'deep', 'repair'}",
                     'always',
                     'always',
                     'always',
                     'always',
                     "data.verdict == 'fail' and data.plan_revision_count >= 2",
                     "data.verdict == 'pass'",
                     "data.verdict == 'fail' and data.plan_revision_count < 2",
                     'always',
                     "data.verdict == 'fail' and data.repair_count >= 2",
                     "data.verdict == 'fail' and data.repair_count < 2",
                     "data.verdict == 'pass'",
                     "data.verdict == 'fail' and data.repair_count >= 2",
                     "data.verdict == 'fail' and data.repair_count < 2",
                     "data.verdict == 'pass'"],
 'allowed_edge_mask': [[False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [True,
                        True,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        True,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        True,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        True,
                        True,
                        False,
                        False,
                        False],
                       [False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        False,
                        True,
                        True,
                        True]],
 'terminal_mask': [True,
                   False,
                   False,
                   False,
                   True,
                   False,
                   False,
                   False,
                   False,
                   False,
                   False,
                   False]}

COMPILED_GRAPH = CompiledGraphTables(
    name=GRAPH_PAYLOAD['name'],
    version=GRAPH_PAYLOAD['version'],
    schema_hash=GRAPH_PAYLOAD['schema_hash'],
    node_ids=tuple(GRAPH_PAYLOAD['node_ids']),
    edge_keys=tuple(GRAPH_PAYLOAD['edge_keys']),
    edge_sources=tuple(GRAPH_PAYLOAD['edge_sources']),
    edge_targets=tuple(GRAPH_PAYLOAD['edge_targets']),
    edge_priorities=tuple(GRAPH_PAYLOAD['edge_priorities']),
    edge_max_traversals=tuple(GRAPH_PAYLOAD['edge_max_traversals']),
    edge_conditions=tuple(GRAPH_PAYLOAD['edge_conditions']),
    allowed_edge_mask=tuple(tuple(row) for row in GRAPH_PAYLOAD['allowed_edge_mask']),
    terminal_mask=tuple(GRAPH_PAYLOAD['terminal_mask']),
)
